### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/kamelmat-instagram-feed-con-bootsrap#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @kamelmat  ,  ¡Felicidades! 
## Estilo de código y limpieza
- ¡Bien hecho! :heavy_check_mark:
## Mejores prácticas/comentarios
- Muy buen proyecto... poco hay que añadir... quizás que te podrías haber ahorrado el `styles.css` y haber usado una clase de bootstrap para el tamaño de la fuente.

**Comment by kamelmat** [comment]
Gracias @EduardoHernandezGuzman , estoy contento porque me dio mucha guerra pero lo conseguí sacar, es el código más largo que he hecho hasta ahora además.
Lo del tamaño de la fuente, fuí a .CSS porque no conseguí que me funcionara desde bootstrap, utilizaba fs-6 y no me bajaba más el tamaño.

**Comment by EduardoHernandezGuzman** [comment]
Tal como comentas, f-6 es el tamaño más pequeño que tiene bootstrap en sus clases. Para tamaños más pequeños tienes que usar css. Bien hecho!!!
